# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exo < Formula
  desc ""
  homepage "https://exo.deref.io"
  version "2021.10.12"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BenElgar/exo/releases/download/v2021.10.12/exo_managed_2021.10.12_darwin_arm64.tar.gz"
      sha256 "76841bbb45b1310652ac9a1250872551089496da21939cf5e8227909177623f1"
    end
    if Hardware::CPU.intel?
      url "https://github.com/BenElgar/exo/releases/download/v2021.10.12/exo_managed_2021.10.12_darwin_amd64.tar.gz"
      sha256 "3ee85c462836d868f76d7d545f58af312f57f738e4e4222d30970c9c2d7bf253"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BenElgar/exo/releases/download/v2021.10.12/exo_managed_2021.10.12_linux_arm64.tar.gz"
      sha256 "57d328952760d09479416fd2c15c90c70091c42aa3c196c06d24cb2999b31aa2"
    end
    if Hardware::CPU.intel?
      url "https://github.com/BenElgar/exo/releases/download/v2021.10.12/exo_managed_2021.10.12_linux_amd64.tar.gz"
      sha256 "4a6344c1c6de8391949cc3e4bce93bf583946d0fba1daa464ac89c2209b9123b"
    end
  end

  def install
    bin.install "exo"
  end

  test do
    system "#{bin}/exo version"
  end
end
